//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace StandardTemplate
{
    
    
    public class StandardTemplate1 : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel9;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel10;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel11;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem2;
        
        public StandardTemplate1()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel9 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel10 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel11 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.menuItem2 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.tpsLabel6);
            this.groupBox1.Controls.Add(this.tpsLabel7);
            this.groupBox1.Controls.Add(this.tpsLabel8);
            this.groupBox1.Controls.Add(this.tpsLabel9);
            this.groupBox1.Controls.Add(this.tpsLabel10);
            this.groupBox1.Controls.Add(this.tpsLabel5);
            this.groupBox1.Controls.Add(this.tpsLabel4);
            this.groupBox1.Controls.Add(this.tpsLabel3);
            this.groupBox1.Controls.Add(this.tpsLabel2);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(15, 31);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(362, 310);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Tuning Increments";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(197, 96);
            this.tpsLabel6.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel6.Title = "1 mm";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(197, 48);
            this.tpsLabel7.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel7.Title = "1 mm/s";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel8.Location = new System.Drawing.Point(197, 144);
            this.tpsLabel8.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel8.Title = "1 V";
            // 
            // tpsLabel9
            // 
            this.tpsLabel9.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel9.Location = new System.Drawing.Point(197, 240);
            this.tpsLabel9.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel9.Title = "1 A";
            // 
            // tpsLabel10
            // 
            this.tpsLabel10.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel10.Location = new System.Drawing.Point(197, 192);
            this.tpsLabel10.Size = new System.Drawing.Size(112, 24);
            this.tpsLabel10.Title = "1";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(25, 96);
            this.tpsLabel5.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel5.Title = "Distance:";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(25, 48);
            this.tpsLabel4.Size = new System.Drawing.Size(115, 24);
            this.tpsLabel4.Title = "Welding speed:";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(25, 144);
            this.tpsLabel3.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel3.Title = "Voltage:";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(25, 240);
            this.tpsLabel2.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel2.Title = "Current:";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(25, 192);
            this.tpsLabel1.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel1.Title = "Control:";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.tpsLabel11);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(395, 31);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(231, 310);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "System Settigs";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel11
            // 
            this.tpsLabel11.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel11.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel11.Location = new System.Drawing.Point(16, 39);
            this.tpsLabel11.Size = new System.Drawing.Size(182, 24);
            this.tpsLabel11.Title = "Select active welding system";
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.MenuItems.Add(this.menuItem2);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = true;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "OK";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            // 
            // menuItem2
            // 
            this.menuItem2.Checked = true;
            this.menuItem2.DockToRight = true;
            this.menuItem2.Enabled = true;
            this.menuItem2.Index = 1;
            this.menuItem2.Pressed = false;
            this.menuItem2.Text = "Close";
            this.menuItem2.Toggle = false;
            this.menuItem2.Width = 128;
            // 
            // StandardTemplate1
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.commandBar1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Text = "Settings";
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
    }
}
