//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace SCM_ExampleProject
{
    
    
    public class Access : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBoxRobot;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblRobotState;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RapidExecutionStatus rapidExecutionStatus1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBoxAccess;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblRequest;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblAccess;
        
        private ABB.Robotics.Tps.Windows.Forms.Led ledAccess;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.ControllerModeStatus controllerModeStatus1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblControllerMode;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btnClose;
        
        public Access()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.btnClose = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.groupBoxRobot = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.rapidExecutionStatus1 = new ABB.Robotics.ScreenMaker.Windows.Forms.RapidExecutionStatus();
            this.controllerModeStatus1 = new ABB.Robotics.ScreenMaker.Windows.Forms.ControllerModeStatus();
            this.lblControllerMode = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lblRobotState = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBoxAccess = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.lblAccess = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.ledAccess = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.lblRequest = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBoxRobot.SuspendLayout();
            this.groupBoxAccess.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnClose
            // 
            this.btnClose.BackColor = System.Drawing.Color.White;
            this.btnClose.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.btnClose.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnClose.Location = new System.Drawing.Point(547, 338);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(92, 52);
            this.btnClose.Text = "Close";
            this.btnClose.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // groupBoxRobot
            // 
            this.groupBoxRobot.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxRobot.AutoScroll = false;
            this.groupBoxRobot.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBoxRobot.Controls.Add(this.rapidExecutionStatus1);
            this.groupBoxRobot.Controls.Add(this.controllerModeStatus1);
            this.groupBoxRobot.Controls.Add(this.lblControllerMode);
            this.groupBoxRobot.Controls.Add(this.lblRobotState);
            this.groupBoxRobot.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBoxRobot.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.groupBoxRobot.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBoxRobot.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBoxRobot.Location = new System.Drawing.Point(22, 67);
            this.groupBoxRobot.Name = "groupBoxRobot";
            this.groupBoxRobot.Size = new System.Drawing.Size(207, 259);
            this.groupBoxRobot.Tag = null;
            this.groupBoxRobot.Title = "Robot Status";
            this.groupBoxRobot.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // rapidExecutionStatus1
            // 
            this.rapidExecutionStatus1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.rapidExecutionStatus1.Location = new System.Drawing.Point(147, 172);
            this.rapidExecutionStatus1.Name = "rapidExecutionStatus1";
            this.rapidExecutionStatus1.Size = new System.Drawing.Size(45, 45);
            // 
            // controllerModeStatus1
            // 
            this.controllerModeStatus1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.controllerModeStatus1.Location = new System.Drawing.Point(147, 34);
            this.controllerModeStatus1.Name = "controllerModeStatus1";
            this.controllerModeStatus1.Size = new System.Drawing.Size(45, 43);
            // 
            // lblControllerMode
            // 
            this.lblControllerMode.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.lblControllerMode.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblControllerMode.Location = new System.Drawing.Point(68, 34);
            this.lblControllerMode.Multiline = true;
            this.lblControllerMode.Name = "lblControllerMode";
            this.lblControllerMode.Size = new System.Drawing.Size(100, 24);
            this.lblControllerMode.Title = "Mode:";
            // 
            // lblRobotState
            // 
            this.lblRobotState.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.lblRobotState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblRobotState.Location = new System.Drawing.Point(50, 172);
            this.lblRobotState.Multiline = true;
            this.lblRobotState.Name = "lblRobotState";
            this.lblRobotState.Size = new System.Drawing.Size(104, 24);
            this.lblRobotState.Title = "Execution:";
            // 
            // groupBoxAccess
            // 
            this.groupBoxAccess.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxAccess.AutoScroll = false;
            this.groupBoxAccess.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBoxAccess.Controls.Add(this.lblAccess);
            this.groupBoxAccess.Controls.Add(this.ledAccess);
            this.groupBoxAccess.Controls.Add(this.button1);
            this.groupBoxAccess.Controls.Add(this.lblRequest);
            this.groupBoxAccess.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBoxAccess.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.groupBoxAccess.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBoxAccess.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBoxAccess.Location = new System.Drawing.Point(312, 67);
            this.groupBoxAccess.Name = "groupBoxAccess";
            this.groupBoxAccess.Size = new System.Drawing.Size(295, 259);
            this.groupBoxAccess.Tag = null;
            this.groupBoxAccess.Title = "Access Control";
            this.groupBoxAccess.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // lblAccess
            // 
            this.lblAccess.AllowMultipleStates = true;
            this.lblAccess.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diAccessOK")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.lblAccess.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.lblAccess.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblAccess.Location = new System.Drawing.Point(51, 125);
            this.lblAccess.Multiline = true;
            this.lblAccess.Name = "lblAccess";
            this.lblAccess.Size = new System.Drawing.Size(112, 24);
            stateObject1.Add("Text", "NO ACCESS");
            stateObject2.Add("Text", "ACCESS OK");
            this.lblAccess.States.Add(stateObject1);
            this.lblAccess.States.Add(stateObject2);
            this.lblAccess.Title = "NO ACCESS";
            stateObject3.Add("Text", "tpsLabel1");
            this.lblAccess.UndefinedState = stateObject3;
            // 
            // ledAccess
            // 
            this.ledAccess.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diAccessOK")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.ledAccess.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.ledAccess.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ledAccess.Location = new System.Drawing.Point(180, 121);
            this.ledAccess.Name = "ledAccess";
            this.ledAccess.Size = new System.Drawing.Size(180, 36);
            this.ledAccess.Text = "Access";
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(180, 34);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(85, 58);
            this.button1.Text = "Request";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // lblRequest
            // 
            this.lblRequest.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.lblRequest.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblRequest.Location = new System.Drawing.Point(36, 34);
            this.lblRequest.Multiline = true;
            this.lblRequest.Name = "lblRequest";
            this.lblRequest.Size = new System.Drawing.Size(138, 24);
            this.lblRequest.Title = "Press to Access:";
            // 
            // Access
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.groupBoxAccess);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.groupBoxRobot);
            this.Text = "Cell and Gate Access Handling";
            this.Controls.SetChildIndex(this.groupBoxRobot, 0);
            this.Controls.SetChildIndex(this.btnClose, 0);
            this.Controls.SetChildIndex(this.groupBoxAccess, 0);
            this.groupBoxRobot.ResumeLayout(false);
            this.groupBoxAccess.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void btnClose_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnClose_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doGateRequestAccess"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
