//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace SCM_ExampleProject
{
    
    
    public class Conveyor : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button btnForward;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btnReverse;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBoxDirection;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBoxSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButtonLow;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButtonHigh;
        
        private ABB.Robotics.Tps.Windows.Forms.Led ledReverse;
        
        private ABB.Robotics.Tps.Windows.Forms.Led ledForward;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.ActionTrigger actionTriggerClose;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLblSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btnClose;
        
        public Conveyor()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.btnClose = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.btnForward = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.btnReverse = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.groupBoxDirection = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.ledReverse = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.ledForward = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBoxSpeed = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.radioButtonLow = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButtonHigh = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.actionTriggerClose = new ABB.Robotics.ScreenMaker.Windows.Forms.ActionTrigger();
            this.tpsLblSpeed = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBoxDirection.SuspendLayout();
            this.groupBoxSpeed.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.actionTriggerClose)).BeginInit();
            this.SuspendLayout();
            // 
            // btnClose
            // 
            this.btnClose.BackColor = System.Drawing.Color.White;
            this.btnClose.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.btnClose.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnClose.Location = new System.Drawing.Point(547, 338);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(92, 52);
            this.btnClose.Text = "Close";
            this.btnClose.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btnClose.Click += new System.EventHandler(this.button1_Click);
            // 
            // btnForward
            // 
            this.btnForward.BackColor = System.Drawing.Color.White;
            this.btnForward.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.btnForward.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnForward.Image = ((System.Drawing.Image)(resources.GetObject("btnForward.Image")));
            this.btnForward.Location = new System.Drawing.Point(179, 48);
            this.btnForward.Name = "btnForward";
            this.btnForward.Size = new System.Drawing.Size(122, 70);
            this.btnForward.Text = "Forward";
            this.btnForward.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btnForward.Click += new System.EventHandler(this.btnForward_Click);
            this.btnForward.MouseDown += new System.Windows.Forms.MouseEventHandler(this.btnForward_MouseDown);
            this.btnForward.MouseUp += new System.Windows.Forms.MouseEventHandler(this.btnForward_MouseUp);
            // 
            // btnReverse
            // 
            this.btnReverse.BackColor = System.Drawing.Color.White;
            this.btnReverse.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.btnReverse.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnReverse.Image = ((System.Drawing.Image)(resources.GetObject("btnReverse.Image")));
            this.btnReverse.Location = new System.Drawing.Point(42, 48);
            this.btnReverse.Name = "btnReverse";
            this.btnReverse.Size = new System.Drawing.Size(120, 70);
            this.btnReverse.Text = "Reverse";
            this.btnReverse.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btnReverse.Click += new System.EventHandler(this.btnReverse_Click);
            this.btnReverse.MouseDown += new System.Windows.Forms.MouseEventHandler(this.btnReverse_MouseDown);
            this.btnReverse.MouseUp += new System.Windows.Forms.MouseEventHandler(this.btnReverse_MouseUp);
            // 
            // groupBoxDirection
            // 
            this.groupBoxDirection.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxDirection.AutoScroll = false;
            this.groupBoxDirection.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBoxDirection.Controls.Add(this.ledReverse);
            this.groupBoxDirection.Controls.Add(this.ledForward);
            this.groupBoxDirection.Controls.Add(this.btnReverse);
            this.groupBoxDirection.Controls.Add(this.btnForward);
            this.groupBoxDirection.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBoxDirection.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.groupBoxDirection.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBoxDirection.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBoxDirection.Location = new System.Drawing.Point(13, 58);
            this.groupBoxDirection.Name = "groupBoxDirection";
            this.groupBoxDirection.Size = new System.Drawing.Size(334, 231);
            this.groupBoxDirection.Tag = null;
            this.groupBoxDirection.Title = "Direction";
            this.groupBoxDirection.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // ledReverse
            // 
            this.ledReverse.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diConveyorReverse")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.ledReverse.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.ledReverse.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ledReverse.Location = new System.Drawing.Point(96, 124);
            this.ledReverse.Name = "ledReverse";
            this.ledReverse.Size = new System.Drawing.Size(66, 36);
            this.ledReverse.Text = "";
            // 
            // ledForward
            // 
            this.ledForward.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diConveyorForward")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.ledForward.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.ledForward.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ledForward.Location = new System.Drawing.Point(217, 124);
            this.ledForward.Name = "ledForward";
            this.ledForward.Size = new System.Drawing.Size(36, 36);
            this.ledForward.Text = "";
            // 
            // groupBoxSpeed
            // 
            this.groupBoxSpeed.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxSpeed.AutoScroll = false;
            this.groupBoxSpeed.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBoxSpeed.Controls.Add(this.radioButtonLow);
            this.groupBoxSpeed.Controls.Add(this.radioButtonHigh);
            this.groupBoxSpeed.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBoxSpeed.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.groupBoxSpeed.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBoxSpeed.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBoxSpeed.Location = new System.Drawing.Point(396, 58);
            this.groupBoxSpeed.Name = "groupBoxSpeed";
            this.groupBoxSpeed.Size = new System.Drawing.Size(223, 153);
            this.groupBoxSpeed.Tag = null;
            this.groupBoxSpeed.Title = "Speed";
            this.groupBoxSpeed.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // radioButtonLow
            // 
            this.radioButtonLow.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.radioButtonLow.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButtonLow.Location = new System.Drawing.Point(24, 82);
            this.radioButtonLow.Name = "radioButtonLow";
            this.radioButtonLow.Size = new System.Drawing.Size(180, 36);
            this.radioButtonLow.Text = "Low";
            this.radioButtonLow.CheckedChanged += new System.EventHandler(this.radioButtonLow_CheckedChanged);
            // 
            // radioButtonHigh
            // 
            this.radioButtonHigh.Checked = true;
            this.radioButtonHigh.DataBindings.Add(new System.Windows.Forms.Binding("Checked", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doConveyorSpeed")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.radioButtonHigh.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.radioButtonHigh.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButtonHigh.Location = new System.Drawing.Point(24, 29);
            this.radioButtonHigh.Name = "radioButtonHigh";
            this.radioButtonHigh.Size = new System.Drawing.Size(180, 36);
            this.radioButtonHigh.Text = "High";
            this.radioButtonHigh.CheckedChanged += new System.EventHandler(this.radioButtonHigh_CheckedChanged);
            // 
            // actionTriggerClose
            // 
            this.actionTriggerClose.Trigger += new System.EventHandler(this.Close);
            this.actionTriggerClose.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doConveyorSpeed")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            // 
            // tpsLblSpeed
            // 
            this.tpsLblSpeed.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.tpsLblSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLblSpeed.Location = new System.Drawing.Point(13, 295);
            this.tpsLblSpeed.Multiline = true;
            this.tpsLblSpeed.Name = "tpsLblSpeed";
            this.tpsLblSpeed.Size = new System.Drawing.Size(334, 68);
            this.tpsLblSpeed.Title = "Changing the State of Speed will Close the Screen describing the use of Action Tr" +
                "igger Control";
            this.tpsLblSpeed.WordWrap = true;
            // 
            // Conveyor
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.tpsLblSpeed);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.groupBoxSpeed);
            this.Controls.Add(this.groupBoxDirection);
            this.Text = "Conveyor";
            this.Controls.SetChildIndex(this.groupBoxDirection, 0);
            this.Controls.SetChildIndex(this.groupBoxSpeed, 0);
            this.Controls.SetChildIndex(this.btnClose, 0);
            this.Controls.SetChildIndex(this.tpsLblSpeed, 0);
            this.groupBoxDirection.ResumeLayout(false);
            this.groupBoxSpeed.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.actionTriggerClose)).EndInit();
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btnForward_MouseDown(object sender, System.Windows.Forms.MouseEventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnForward_MouseDown", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btnForward_MouseUp(object sender, System.Windows.Forms.MouseEventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnForward_MouseUp", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btnReverse_MouseDown(object sender, System.Windows.Forms.MouseEventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnReverse_MouseDown", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btnReverse_MouseUp(object sender, System.Windows.Forms.MouseEventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnReverse_MouseUp", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void radioButtonHigh_CheckedChanged(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in radioButtonHigh_CheckedChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void radioButtonLow_CheckedChanged(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in radioButtonLow_CheckedChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void Close(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Close", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btnReverse_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalReset
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doConveyorForward"))).Reset();
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doConveyorReverse"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnReverse_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btnForward_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalReset
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doConveyorReverse"))).Reset();
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doConveyorForward"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btnForward_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
