//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace SCM_ExampleProject
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar MainScreenCommand;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem MenuItemAccess;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItemConveyor;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItemMotor;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox imageLayout;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox imageBar;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblGateStatus;
        
        private ABB.Robotics.Tps.Windows.Forms.ComboBox comboBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblRollerDiameter;
        
        private ABB.Robotics.Tps.Windows.Forms.Switch switchToggleGate;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItemRoutines;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.MainScreenCommand = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.MenuItemAccess = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.menuItemConveyor = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.menuItemMotor = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.menuItemRoutines = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.imageLayout = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.imageBar = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.lblGateStatus = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.comboBox1 = new ABB.Robotics.Tps.Windows.Forms.ComboBox();
            this.lblRollerDiameter = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.switchToggleGate = new ABB.Robotics.Tps.Windows.Forms.Switch();
            this.SuspendLayout();
            // 
            // MainScreenCommand
            // 
            this.MainScreenCommand.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.MainScreenCommand.Location = new System.Drawing.Point(0, 347);
            this.MainScreenCommand.MenuItems.Add(this.MenuItemAccess);
            this.MainScreenCommand.MenuItems.Add(this.menuItemConveyor);
            this.MainScreenCommand.MenuItems.Add(this.menuItemMotor);
            this.MainScreenCommand.MenuItems.Add(this.menuItemRoutines);
            this.MainScreenCommand.Name = "MainScreenCommand";
            this.MainScreenCommand.Size = new System.Drawing.Size(639, 43);
            // 
            // MenuItemAccess
            // 
            this.MenuItemAccess.Checked = false;
            this.MenuItemAccess.DockToRight = false;
            this.MenuItemAccess.Enabled = true;
            this.MenuItemAccess.Index = 0;
            this.MenuItemAccess.Pressed = false;
            this.MenuItemAccess.Text = "Access";
            this.MenuItemAccess.Toggle = false;
            this.MenuItemAccess.Width = 128;
            this.MenuItemAccess.Click += new System.EventHandler(this.MenuItemAccess_Click);
            // 
            // menuItemConveyor
            // 
            this.menuItemConveyor.Checked = false;
            this.menuItemConveyor.DockToRight = false;
            this.menuItemConveyor.Enabled = true;
            this.menuItemConveyor.Index = 1;
            this.menuItemConveyor.Pressed = false;
            this.menuItemConveyor.Text = "Conveyor";
            this.menuItemConveyor.Toggle = false;
            this.menuItemConveyor.Width = 128;
            this.menuItemConveyor.Click += new System.EventHandler(this.menuItemConveyor_Click);
            // 
            // menuItemMotor
            // 
            this.menuItemMotor.Checked = false;
            this.menuItemMotor.DockToRight = false;
            this.menuItemMotor.Enabled = true;
            this.menuItemMotor.Index = 2;
            this.menuItemMotor.Pressed = false;
            this.menuItemMotor.Text = "Motor";
            this.menuItemMotor.Toggle = false;
            this.menuItemMotor.Width = 128;
            this.menuItemMotor.Click += new System.EventHandler(this.menuItemMotor_Click);
            // 
            // menuItemRoutines
            // 
            this.menuItemRoutines.Checked = false;
            this.menuItemRoutines.DockToRight = false;
            this.menuItemRoutines.Enabled = true;
            this.menuItemRoutines.Index = 3;
            this.menuItemRoutines.Pressed = false;
            this.menuItemRoutines.Text = "Routines";
            this.menuItemRoutines.Toggle = false;
            this.menuItemRoutines.Width = 128;
            this.menuItemRoutines.Click += new System.EventHandler(this.menuItemRoutines_Click);
            // 
            // imageLayout
            // 
            this.imageLayout.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.imageLayout.Image = ((System.Drawing.Image)(resources.GetObject("imageLayout.Image")));
            this.imageLayout.Location = new System.Drawing.Point(98, 31);
            this.imageLayout.Name = "imageLayout";
            this.imageLayout.Size = new System.Drawing.Size(643, 328);
            // 
            // imageBar
            // 
            this.imageBar.AllowMultipleStates = true;
            this.imageBar.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diLightCurtainStatus")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.imageBar.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.imageBar.Image = ((System.Drawing.Image)(resources.GetObject("imageBar.Image")));
            this.imageBar.Location = new System.Drawing.Point(365, 300);
            this.imageBar.Name = "imageBar";
            this.imageBar.Size = new System.Drawing.Size(105, 15);
            stateObject1.Add("Image", ((System.Drawing.Bitmap)(resources.GetObject("imageBar.States"))));
            stateObject2.Add("Image", ((System.Drawing.Bitmap)(resources.GetObject("imageBar.States1"))));
            this.imageBar.States.Add(stateObject1);
            this.imageBar.States.Add(stateObject2);
            stateObject3.Add("Image", ((System.Drawing.Bitmap)(resources.GetObject("imageBar.UndefinedState"))));
            this.imageBar.UndefinedState = stateObject3;
            // 
            // lblGateStatus
            // 
            this.lblGateStatus.BackColor = System.Drawing.Color.Gainsboro;
            this.lblGateStatus.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.lblGateStatus.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblGateStatus.Location = new System.Drawing.Point(472, 300);
            this.lblGateStatus.Multiline = true;
            this.lblGateStatus.Name = "lblGateStatus";
            this.lblGateStatus.Size = new System.Drawing.Size(104, 24);
            this.lblGateStatus.Title = "Gate Status";
            // 
            // comboBox1
            // 
            this.comboBox1.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "rollerData", "rollSize")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.comboBox1.DataBindings.Add(new System.Windows.Forms.Binding("SelectedIndex", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "rollerData", "rollSizeIndex")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.comboBox1.DataSource = new ABB.Robotics.ScreenMaker.Windows.Forms.ArrayBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "rollerData", "allowedRollSizes"), new ABB.Robotics.ScreenMaker.Windows.Forms.Index[] {
                        new ABB.Robotics.ScreenMaker.Windows.Forms.Index(5)});
            this.comboBox1.DisplayMember = "Value";
            this.comboBox1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.comboBox1.Location = new System.Drawing.Point(30, 110);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(150, 30);
            this.comboBox1.ValueMember = "Value";
            // 
            // lblRollerDiameter
            // 
            this.lblRollerDiameter.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.lblRollerDiameter.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblRollerDiameter.Location = new System.Drawing.Point(30, 80);
            this.lblRollerDiameter.Multiline = true;
            this.lblRollerDiameter.Name = "lblRollerDiameter";
            this.lblRollerDiameter.Size = new System.Drawing.Size(150, 24);
            this.lblRollerDiameter.Title = "Roller Diameter";
            // 
            // switchToggleGate
            // 
            this.switchToggleGate.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doLightCurtainReset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.switchToggleGate.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.switchToggleGate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.switchToggleGate.Location = new System.Drawing.Point(30, 190);
            this.switchToggleGate.Name = "switchToggleGate";
            this.switchToggleGate.Size = new System.Drawing.Size(180, 36);
            this.switchToggleGate.Text = "Reset";
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.switchToggleGate);
            this.Controls.Add(this.lblRollerDiameter);
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.MainScreenCommand);
            this.Controls.Add(this.imageBar);
            this.Controls.Add(this.lblGateStatus);
            this.Controls.Add(this.imageLayout);
            this.Text = "ABB ScreenMaker Example";
            this.Controls.SetChildIndex(this.imageLayout, 0);
            this.Controls.SetChildIndex(this.lblGateStatus, 0);
            this.Controls.SetChildIndex(this.imageBar, 0);
            this.Controls.SetChildIndex(this.MainScreenCommand, 0);
            this.Controls.SetChildIndex(this.comboBox1, 0);
            this.Controls.SetChildIndex(this.lblRollerDiameter, 0);
            this.Controls.SetChildIndex(this.switchToggleGate, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void MenuItemAccess_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.ShowScreen(typeof(Access));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in MenuItemAccess_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void menuItemConveyor_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.ShowScreen(typeof(Conveyor));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in menuItemConveyor_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void menuItemMotor_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.ShowScreen(typeof(Motor));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in menuItemMotor_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void menuItemRoutines_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.ShowScreen(typeof(Routines));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in menuItemRoutines_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
