//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace SCM_ExampleProject
{
    
    
    public class Routines : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton runRoutineHome;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        public Routines()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.runRoutineHome = new ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(547, 338);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(92, 52);
            this.button1.Text = "Close";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // runRoutineHome
            // 
            this.runRoutineHome.BackColor = System.Drawing.Color.White;
            this.runRoutineHome.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold);
            this.runRoutineHome.ForeColor = System.Drawing.SystemColors.ControlText;
            this.runRoutineHome.Location = new System.Drawing.Point(41, 81);
            this.runRoutineHome.Name = "runRoutineHome";
            this.runRoutineHome.RoutineToCall = new ABB.Robotics.ScreenMaker.Windows.Forms.RoutineDataObject("T_ROB1", "Routines", "main");
            this.runRoutineHome.Size = new System.Drawing.Size(140, 70);
            this.runRoutineHome.Text = "Robot to Home";
            this.runRoutineHome.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // Routines
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.runRoutineHome);
            this.Controls.Add(this.button1);
            this.Text = "Special Routines";
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.runRoutineHome, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
