<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>6.4</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="86b5cc5d-35d0-495a-b04a-0e857a63ad62" Name="DESKTOP-KTVIQB9" System="IRB4400_60_SCM_Example" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 5.11.1022.0</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.4.108</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>ABB SCM Example</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>0</StartupType>
	</TpsViewInfo>
	<ApplicationVariables />
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MainScreen.view">
			<Link>MainScreen.view</Link>
		</Compile>
		<Compile Include=".\Access.view">
			<Link>Access.view</Link>
		</Compile>
		<Compile Include=".\Conveyor.view">
			<Link>Conveyor.view</Link>
		</Compile>
		<Compile Include=".\Motor.view">
			<Link>Motor.view</Link>
		</Compile>
		<Compile Include=".\Routines.view">
			<Link>Routines.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.4.108</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>