//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace StandardTemplate
{
    
    
    public class Manual : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton runRoutineButton1;
        
        private ABB.Robotics.Tps.Windows.Forms.Switch switch1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RapidExecutionStatus rapidExecutionStatus1;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.ControllerModeStatus controllerModeStatus1;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        public Manual()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.groupBox4 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.runRoutineButton1 = new ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.switch1 = new ABB.Robotics.Tps.Windows.Forms.Switch();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.groupBox3 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.rapidExecutionStatus1 = new ABB.Robotics.ScreenMaker.Windows.Forms.RapidExecutionStatus();
            this.controllerModeStatus1 = new ABB.Robotics.ScreenMaker.Windows.Forms.ControllerModeStatus();
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.groupBox1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.groupBox4);
            this.groupBox1.Controls.Add(this.button2);
            this.groupBox1.Controls.Add(this.button1);
            this.groupBox1.Controls.Add(this.tpsLabel3);
            this.groupBox1.Controls.Add(this.tpsLabel2);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(12, 50);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(254, 291);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Feed";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox4.AutoScroll = false;
            this.groupBox4.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox4.Controls.Add(this.tpsLabel5);
            this.groupBox4.Controls.Add(this.runRoutineButton1);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox4.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox4.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox4.Location = new System.Drawing.Point(0, 185);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(254, 106);
            this.groupBox4.Tag = null;
            this.groupBox4.Title = "";
            this.groupBox4.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(13, 46);
            this.tpsLabel5.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel5.Title = "Run Routine";
            // 
            // runRoutineButton1
            // 
            this.runRoutineButton1.BackColor = System.Drawing.SystemColors.Control;
            this.runRoutineButton1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.runRoutineButton1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.runRoutineButton1.Location = new System.Drawing.Point(119, 28);
            this.runRoutineButton1.Size = new System.Drawing.Size(67, 58);
            this.runRoutineButton1.Text = "R";
            this.runRoutineButton1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Image = ((System.Drawing.Image)(resources.GetObject("button2.Image")));
            this.button2.Location = new System.Drawing.Point(120, 133);
            this.button2.Size = new System.Drawing.Size(66, 46);
            this.button2.Text = "";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Image = ((System.Drawing.Image)(resources.GetObject("button1.Image")));
            this.button1.Location = new System.Drawing.Point(121, 68);
            this.button1.Size = new System.Drawing.Size(66, 46);
            this.button1.Text = "";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(15, 143);
            this.tpsLabel3.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel3.Title = "Backward";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(15, 80);
            this.tpsLabel2.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel2.Title = "Forward";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(14, 28);
            this.tpsLabel1.Size = new System.Drawing.Size(220, 24);
            this.tpsLabel1.Title = "Keep buttons pressed";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.switch1);
            this.groupBox2.Controls.Add(this.tpsLabel6);
            this.groupBox2.Controls.Add(this.button4);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(290, 50);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(335, 127);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Gas";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // switch1
            // 
            this.switch1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.switch1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.switch1.Location = new System.Drawing.Point(214, 68);
            this.switch1.Size = new System.Drawing.Size(107, 36);
            this.switch1.Text = "";
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(16, 19);
            this.tpsLabel6.Size = new System.Drawing.Size(220, 24);
            this.tpsLabel6.Title = "Keep buttons pressed";
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.SystemColors.Control;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button4.ForeColor = System.Drawing.Color.Blue;
            this.button4.Location = new System.Drawing.Point(33, 58);
            this.button4.Size = new System.Drawing.Size(120, 59);
            this.button4.Text = "Press";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox3.AutoScroll = false;
            this.groupBox3.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox3.Controls.Add(this.tpsLabel7);
            this.groupBox3.Controls.Add(this.tpsLabel4);
            this.groupBox3.Controls.Add(this.rapidExecutionStatus1);
            this.groupBox3.Controls.Add(this.controllerModeStatus1);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox3.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox3.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox3.Location = new System.Drawing.Point(290, 183);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(335, 158);
            this.groupBox3.Tag = null;
            this.groupBox3.Title = "Status";
            this.groupBox3.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(33, 104);
            this.tpsLabel7.Size = new System.Drawing.Size(120, 24);
            this.tpsLabel7.Title = "Rapid Execution";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(33, 49);
            this.tpsLabel4.Size = new System.Drawing.Size(120, 24);
            this.tpsLabel4.Title = "Controller Mode";
            // 
            // rapidExecutionStatus1
            // 
            this.rapidExecutionStatus1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.rapidExecutionStatus1.Location = new System.Drawing.Point(209, 88);
            this.rapidExecutionStatus1.Size = new System.Drawing.Size(44, 40);
            // 
            // controllerModeStatus1
            // 
            this.controllerModeStatus1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.controllerModeStatus1.Location = new System.Drawing.Point(209, 38);
            this.controllerModeStatus1.Size = new System.Drawing.Size(44, 44);
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = false;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "Close";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            this.menuItem1.Click += new System.EventHandler(this.Manual_Close);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(516, 3);
            this.pictureBox1.Size = new System.Drawing.Size(123, 45);
            // 
            // Manual
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.commandBar1);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Text = "Manual Functions";
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.groupBox3, 0);
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.groupBox1.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Manual_Close(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Manual_Close", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
