//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace StandardTemplate
{
    
    
    public class Supervise : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel11;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton4;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton3;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton2;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton1;
        
        private ABB.Robotics.Tps.Windows.Forms.ComboBox comboBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        public Supervise()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel11 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.radioButton4 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButton3 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButton2 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButton1 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.comboBox1 = new ABB.Robotics.Tps.Windows.Forms.ComboBox();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = false;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "Close";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            this.menuItem1.Click += new System.EventHandler(this.Close);
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.tpsLabel7);
            this.groupBox2.Controls.Add(this.tpsLabel6);
            this.groupBox2.Controls.Add(this.tpsLabel5);
            this.groupBox2.Controls.Add(this.tpsLabel3);
            this.groupBox2.Controls.Add(this.tpsLabel11);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(394, 54);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(231, 287);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "System";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font14b;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(55, 116);
            this.tpsLabel7.Size = new System.Drawing.Size(96, 24);
            this.tpsLabel7.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel7.Title = "Halted";
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.BackColor = System.Drawing.Color.Red;
            this.tpsLabel6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(63, 146);
            this.tpsLabel6.Size = new System.Drawing.Size(88, 40);
            this.tpsLabel6.Title = "";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.BackColor = System.Drawing.Color.Red;
            this.tpsLabel5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(162, 29);
            this.tpsLabel5.Size = new System.Drawing.Size(34, 24);
            this.tpsLabel5.Title = "";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.tpsLabel3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(107, 29);
            this.tpsLabel3.Size = new System.Drawing.Size(36, 24);
            this.tpsLabel3.Title = "";
            // 
            // tpsLabel11
            // 
            this.tpsLabel11.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel11.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel11.Location = new System.Drawing.Point(33, 29);
            this.tpsLabel11.Size = new System.Drawing.Size(52, 24);
            this.tpsLabel11.Title = "State";
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.radioButton4);
            this.groupBox1.Controls.Add(this.radioButton3);
            this.groupBox1.Controls.Add(this.radioButton2);
            this.groupBox1.Controls.Add(this.radioButton1);
            this.groupBox1.Controls.Add(this.comboBox1);
            this.groupBox1.Controls.Add(this.tpsLabel2);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Controls.Add(this.tpsLabel4);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(14, 54);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(362, 287);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Supervise";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // radioButton4
            // 
            this.radioButton4.Checked = true;
            this.radioButton4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.radioButton4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton4.Location = new System.Drawing.Point(171, 231);
            this.radioButton4.Size = new System.Drawing.Size(145, 36);
            this.radioButton4.Text = "Off";
            // 
            // radioButton3
            // 
            this.radioButton3.Checked = true;
            this.radioButton3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.radioButton3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton3.Location = new System.Drawing.Point(171, 146);
            this.radioButton3.Size = new System.Drawing.Size(145, 36);
            this.radioButton3.Text = "Off";
            // 
            // radioButton2
            // 
            this.radioButton2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.radioButton2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton2.Location = new System.Drawing.Point(25, 231);
            this.radioButton2.Size = new System.Drawing.Size(129, 36);
            this.radioButton2.Text = "On";
            // 
            // radioButton1
            // 
            this.radioButton1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.radioButton1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton1.Location = new System.Drawing.Point(25, 146);
            this.radioButton1.Size = new System.Drawing.Size(129, 36);
            this.radioButton1.Text = "On";
            // 
            // comboBox1
            // 
            this.comboBox1.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", new ABB.Robotics.ScreenMaker.Windows.Forms.ApplicationVariableBindingSource("newName"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.comboBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.comboBox1.Items.Add(new ABB.Robotics.Tps.Windows.Forms.ComboBoxItem("NewItem1", "T_ROB1"));
            this.comboBox1.Location = new System.Drawing.Point(25, 70);
            this.comboBox1.Size = new System.Drawing.Size(265, 30);
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(25, 201);
            this.tpsLabel2.Size = new System.Drawing.Size(154, 24);
            this.tpsLabel2.Title = "Maintenance Mode";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(25, 116);
            this.tpsLabel1.Size = new System.Drawing.Size(147, 24);
            this.tpsLabel1.Title = "Robot Supervision";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(25, 39);
            this.tpsLabel4.Size = new System.Drawing.Size(115, 24);
            this.tpsLabel4.Title = "Task";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(516, 0);
            this.pictureBox1.Size = new System.Drawing.Size(123, 45);
            // 
            // Supervise
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.commandBar1);
            this.Text = "Supervision";
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.groupBox2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Close(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Close", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
