//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: System.Reflection.AssemblyTitleAttribute("")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Code generated by ScreenMaker - Internal version 5.14.0.0")]
[assembly: System.Reflection.AssemblyCompanyAttribute("")]
[assembly: System.Reflection.AssemblyProductAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("")]
[assembly: System.Reflection.AssemblyCultureAttribute("")]
[assembly: System.Reflection.AssemblyVersionAttribute("5.14.131")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("5.14.0.0")]
[assembly: ABB.Robotics.Tps.Taf.TpsViewAttribute("BasicTemplate App", "tpu-Operator32.gif", "tpu-Operator32.gif", "TpsViewBasicTemplate.dll", "BasicTemplate.MainScreen", ABB.Robotics.Tps.Taf.StartPanelLocation.Left, ABB.Robotics.Tps.Taf.TpsViewType.Static, ABB.Robotics.Tps.Taf.TpsViewStartupTypes.Manual)]


