//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace BasicTemplate
{
    
    
    public class MotorControl : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lblMotorSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.NumericUpDown numericUpDown1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBoxMotor;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButtonMotorOff;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButtonMotorOn;
        
        public MotorControl()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.lblMotorSpeed = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numericUpDown1 = new ABB.Robotics.Tps.Windows.Forms.NumericUpDown();
            this.groupBoxMotor = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.radioButtonMotorOff = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButtonMotorOn = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.groupBoxMotor.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblMotorSpeed
            // 
            this.lblMotorSpeed.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lblMotorSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.lblMotorSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lblMotorSpeed.Location = new System.Drawing.Point(9, 33);
            this.lblMotorSpeed.Size = new System.Drawing.Size(138, 24);
            this.lblMotorSpeed.Title = "Motor Speed";
            // 
            // numericUpDown1
            // 
            this.numericUpDown1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numericUpDown1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numericUpDown1.Increment = new decimal(new int[] {
                        5,
                        0,
                        0,
                        65536});
            this.numericUpDown1.Location = new System.Drawing.Point(9, 63);
            this.numericUpDown1.Maximum = new decimal(new int[] {
                        10,
                        0,
                        0,
                        0});
            this.numericUpDown1.Size = new System.Drawing.Size(220, 47);
            this.numericUpDown1.Value = new decimal(new int[] {
                        5,
                        0,
                        0,
                        0});
            // 
            // groupBoxMotor
            // 
            this.groupBoxMotor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxMotor.AutoScroll = false;
            this.groupBoxMotor.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBoxMotor.Controls.Add(this.radioButtonMotorOff);
            this.groupBoxMotor.Controls.Add(this.radioButtonMotorOn);
            this.groupBoxMotor.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBoxMotor.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12;
            this.groupBoxMotor.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBoxMotor.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBoxMotor.Location = new System.Drawing.Point(54, 134);
            this.groupBoxMotor.Name = "groupBoxMotor";
            this.groupBoxMotor.Size = new System.Drawing.Size(230, 136);
            this.groupBoxMotor.Tag = null;
            this.groupBoxMotor.Title = "Control";
            this.groupBoxMotor.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // radioButtonMotorOff
            // 
            this.radioButtonMotorOff.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.radioButtonMotorOff.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButtonMotorOff.Location = new System.Drawing.Point(31, 85);
            this.radioButtonMotorOff.Size = new System.Drawing.Size(180, 36);
            this.radioButtonMotorOff.Text = "Motor Off";
            // 
            // radioButtonMotorOn
            // 
            this.radioButtonMotorOn.Checked = true;
            this.radioButtonMotorOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.radioButtonMotorOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButtonMotorOn.Location = new System.Drawing.Point(31, 33);
            this.radioButtonMotorOn.Size = new System.Drawing.Size(180, 36);
            this.radioButtonMotorOn.Text = "Motor On";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(516, 0);
            this.pictureBox1.Size = new System.Drawing.Size(123, 45);
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = false;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "Close";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            this.menuItem1.Click += new System.EventHandler(this.MotorControl_Close);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.lblMotorSpeed);
            this.groupBox1.Controls.Add(this.numericUpDown1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(347, 134);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(248, 136);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Speed";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // MotorControl
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.commandBar1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.groupBoxMotor);
            this.Text = "Motor Control";
            this.Controls.SetChildIndex(this.groupBoxMotor, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.groupBoxMotor.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void MotorControl_Close(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in MotorControl_Close", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
