//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace BasicTemplate
{
    
    
    public class Status : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led5;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led4;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor4;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor3;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor2;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        public Status()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.barGraph2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.barGraph1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led5 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led4 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.groupBox3 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.numEditor4 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.numEditor3 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.numEditor2 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.numEditor1 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.barGraph2);
            this.groupBox2.Controls.Add(this.barGraph1);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(262, 51);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(362, 156);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Pressure Level";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // barGraph2
            // 
            this.barGraph2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.barGraph2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph2.Location = new System.Drawing.Point(246, 20);
            this.barGraph2.Size = new System.Drawing.Size(37, 123);
            // 
            // barGraph1
            // 
            this.barGraph1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.barGraph1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph1.Location = new System.Drawing.Point(59, 20);
            this.barGraph1.Size = new System.Drawing.Size(37, 123);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.led1);
            this.groupBox1.Controls.Add(this.led5);
            this.groupBox1.Controls.Add(this.led4);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(14, 41);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(242, 166);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "System Status";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // led1
            // 
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(32, 117);
            this.led1.Size = new System.Drawing.Size(131, 36);
            this.led1.Text = "Fault";
            // 
            // led5
            // 
            this.led5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led5.Location = new System.Drawing.Point(32, 72);
            this.led5.Size = new System.Drawing.Size(131, 36);
            this.led5.Text = "Active";
            // 
            // led4
            // 
            this.led4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led4.Location = new System.Drawing.Point(32, 30);
            this.led4.Size = new System.Drawing.Size(131, 36);
            this.led4.Text = "Ready";
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = false;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "Motor Control";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            this.menuItem1.Click += new System.EventHandler(this.MotorControl_Click);
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox3.AutoScroll = false;
            this.groupBox3.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox3.Controls.Add(this.numEditor4);
            this.groupBox3.Controls.Add(this.numEditor3);
            this.groupBox3.Controls.Add(this.numEditor2);
            this.groupBox3.Controls.Add(this.numEditor1);
            this.groupBox3.Controls.Add(this.tpsLabel5);
            this.groupBox3.Controls.Add(this.tpsLabel4);
            this.groupBox3.Controls.Add(this.tpsLabel2);
            this.groupBox3.Controls.Add(this.tpsLabel1);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox3.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox3.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox3.Location = new System.Drawing.Point(14, 213);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(610, 128);
            this.groupBox3.Tag = null;
            this.groupBox3.Title = "Parameters";
            this.groupBox3.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // numEditor4
            // 
            this.numEditor4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor4.Location = new System.Drawing.Point(429, 72);
            this.numEditor4.Size = new System.Drawing.Size(160, 40);
            this.numEditor4.Value = new decimal(new int[] {
                        30,
                        0,
                        0,
                        0});
            // 
            // numEditor3
            // 
            this.numEditor3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor3.Location = new System.Drawing.Point(429, 26);
            this.numEditor3.Size = new System.Drawing.Size(160, 40);
            this.numEditor3.Value = new decimal(new int[] {
                        5,
                        0,
                        0,
                        0});
            // 
            // numEditor2
            // 
            this.numEditor2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor2.Location = new System.Drawing.Point(97, 72);
            this.numEditor2.Size = new System.Drawing.Size(160, 40);
            this.numEditor2.Value = new decimal(new int[] {
                        20,
                        0,
                        0,
                        0});
            // 
            // numEditor1
            // 
            this.numEditor1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor1.Location = new System.Drawing.Point(97, 26);
            this.numEditor1.Size = new System.Drawing.Size(160, 40);
            this.numEditor1.Value = new decimal(new int[] {
                        10,
                        0,
                        0,
                        0});
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(330, 72);
            this.tpsLabel5.Size = new System.Drawing.Size(75, 24);
            this.tpsLabel5.Title = "Width:";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(330, 26);
            this.tpsLabel4.Size = new System.Drawing.Size(93, 24);
            this.tpsLabel4.Title = "Frequency:";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(24, 72);
            this.tpsLabel2.Size = new System.Drawing.Size(57, 24);
            this.tpsLabel2.Title = "Speed:";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(24, 26);
            this.tpsLabel1.Size = new System.Drawing.Size(66, 24);
            this.tpsLabel1.Title = "Length:";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(516, 0);
            this.pictureBox1.Size = new System.Drawing.Size(123, 45);
            // 
            // Status
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.commandBar1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Text = "Status";
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.Controls.SetChildIndex(this.groupBox3, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.groupBox2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void MotorControl_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MotorControl));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in MotorControl_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
