//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace ExtendedTemplate
{
    
    
    public class Define : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel9;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel10;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel11;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel12;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.DataEditor dataEditor1;
        
        private ABB.Robotics.Tps.Windows.Forms.ComboBox comboBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.ComboBox comboBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.ComboBox comboBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        public Define()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.dataEditor1 = new ABB.Robotics.Tps.Windows.Forms.DataEditor();
            this.comboBox3 = new ABB.Robotics.Tps.Windows.Forms.ComboBox();
            this.comboBox2 = new ABB.Robotics.Tps.Windows.Forms.ComboBox();
            this.comboBox1 = new ABB.Robotics.Tps.Windows.Forms.ComboBox();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel9 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel10 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel11 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel12 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(24, 35);
            this.tpsLabel1.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel1.Title = "Name:";
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.pictureBox1);
            this.groupBox1.Controls.Add(this.dataEditor1);
            this.groupBox1.Controls.Add(this.comboBox3);
            this.groupBox1.Controls.Add(this.comboBox2);
            this.groupBox1.Controls.Add(this.comboBox1);
            this.groupBox1.Controls.Add(this.tpsLabel5);
            this.groupBox1.Controls.Add(this.tpsLabel4);
            this.groupBox1.Controls.Add(this.tpsLabel3);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(0, 21);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(639, 189);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(516, -21);
            this.pictureBox1.Size = new System.Drawing.Size(123, 45);
            // 
            // dataEditor1
            // 
            this.dataEditor1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.dataEditor1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dataEditor1.Location = new System.Drawing.Point(225, 35);
            this.dataEditor1.Size = new System.Drawing.Size(386, 30);
            this.dataEditor1.Text = "";
            // 
            // comboBox3
            // 
            this.comboBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.comboBox3.Location = new System.Drawing.Point(225, 71);
            this.comboBox3.Size = new System.Drawing.Size(386, 30);
            // 
            // comboBox2
            // 
            this.comboBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.comboBox2.Location = new System.Drawing.Point(225, 144);
            this.comboBox2.Size = new System.Drawing.Size(386, 30);
            // 
            // comboBox1
            // 
            this.comboBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.comboBox1.Location = new System.Drawing.Point(225, 107);
            this.comboBox1.Size = new System.Drawing.Size(386, 30);
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(24, 107);
            this.tpsLabel5.Size = new System.Drawing.Size(117, 24);
            this.tpsLabel5.Title = "Tool Data:";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(24, 144);
            this.tpsLabel4.Size = new System.Drawing.Size(135, 24);
            this.tpsLabel4.Title = "Device name:";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(24, 71);
            this.tpsLabel3.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel3.Title = "Task:";
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(189, 216);
            this.tpsLabel6.Size = new System.Drawing.Size(264, 24);
            this.tpsLabel6.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel6.Title = "Joint definitions";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(24, 250);
            this.tpsLabel7.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel7.Title = "Left joint:";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel8.Location = new System.Drawing.Point(24, 280);
            this.tpsLabel8.Size = new System.Drawing.Size(117, 24);
            this.tpsLabel8.Title = "Right joint:";
            // 
            // tpsLabel9
            // 
            this.tpsLabel9.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel9.Location = new System.Drawing.Point(24, 310);
            this.tpsLabel9.Size = new System.Drawing.Size(117, 24);
            this.tpsLabel9.Title = "Butt joint:";
            // 
            // tpsLabel10
            // 
            this.tpsLabel10.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel10.Location = new System.Drawing.Point(239, 250);
            this.tpsLabel10.Size = new System.Drawing.Size(263, 24);
            this.tpsLabel10.Title = "";
            // 
            // tpsLabel11
            // 
            this.tpsLabel11.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel11.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel11.Location = new System.Drawing.Point(239, 280);
            this.tpsLabel11.Size = new System.Drawing.Size(263, 24);
            this.tpsLabel11.Title = "";
            // 
            // tpsLabel12
            // 
            this.tpsLabel12.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel12.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel12.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel12.Location = new System.Drawing.Point(239, 310);
            this.tpsLabel12.Size = new System.Drawing.Size(263, 24);
            this.tpsLabel12.Title = "";
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(544, 238);
            this.button1.Size = new System.Drawing.Size(67, 29);
            this.button1.Text = "...";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(544, 273);
            this.button2.Size = new System.Drawing.Size(67, 29);
            this.button2.Text = "...";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.SystemColors.Control;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(544, 305);
            this.button3.Size = new System.Drawing.Size(67, 29);
            this.button3.Text = "...";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = false;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "Close";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            this.menuItem1.Click += new System.EventHandler(this.Define_Close);
            // 
            // Define
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.commandBar1);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.tpsLabel12);
            this.Controls.Add(this.tpsLabel11);
            this.Controls.Add(this.tpsLabel10);
            this.Controls.Add(this.tpsLabel9);
            this.Controls.Add(this.tpsLabel8);
            this.Controls.Add(this.tpsLabel7);
            this.Controls.Add(this.tpsLabel6);
            this.Controls.Add(this.groupBox1);
            this.Text = "Define";
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.tpsLabel6, 0);
            this.Controls.SetChildIndex(this.tpsLabel7, 0);
            this.Controls.SetChildIndex(this.tpsLabel8, 0);
            this.Controls.SetChildIndex(this.tpsLabel9, 0);
            this.Controls.SetChildIndex(this.tpsLabel10, 0);
            this.Controls.SetChildIndex(this.tpsLabel11, 0);
            this.Controls.SetChildIndex(this.tpsLabel12, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Define_Close(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Define_Close", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
