//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace ExtendedTemplate
{
    
    
    public class ExecutionStatus : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel14;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel13;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel12;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel11;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel10;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel9;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.CommandBar commandBar1;
        
        private ABB.Robotics.Tps.Windows.Forms.MenuItem menuItem1;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox4;
        
        public ExecutionStatus()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led2 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox3 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox4 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel14 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel13 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel12 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel11 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel10 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel9 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.commandBar1 = new ABB.Robotics.Tps.Windows.Forms.CommandBar();
            this.menuItem1 = new ABB.Robotics.Tps.Windows.Forms.MenuItem();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.led3);
            this.groupBox1.Controls.Add(this.led2);
            this.groupBox1.Controls.Add(this.led1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(15, 46);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(597, 75);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Process Signals";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // led3
            // 
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(463, 21);
            this.led3.Size = new System.Drawing.Size(98, 36);
            this.led3.Text = "Shape";
            // 
            // led2
            // 
            this.led2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led2.Location = new System.Drawing.Point(241, 21);
            this.led2.Size = new System.Drawing.Size(107, 36);
            this.led2.Text = "Atom";
            // 
            // led1
            // 
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(32, 21);
            this.led1.Size = new System.Drawing.Size(115, 36);
            this.led1.Text = "Fluid";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.tpsLabel6);
            this.groupBox2.Controls.Add(this.tpsLabel5);
            this.groupBox2.Controls.Add(this.tpsLabel2);
            this.groupBox2.Controls.Add(this.tpsLabel1);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(15, 127);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(292, 88);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Executing Program";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(133, 52);
            this.tpsLabel6.Size = new System.Drawing.Size(118, 24);
            this.tpsLabel6.Title = "M4";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(133, 22);
            this.tpsLabel5.Size = new System.Drawing.Size(118, 24);
            this.tpsLabel5.Title = "T_ROB1";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(14, 53);
            this.tpsLabel2.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel2.Title = "Program:";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(14, 22);
            this.tpsLabel1.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel1.Title = "Task:";
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox3.AutoScroll = false;
            this.groupBox3.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox3.Controls.Add(this.tpsLabel4);
            this.groupBox3.Controls.Add(this.tpsLabel3);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox3.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox3.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox3.Location = new System.Drawing.Point(15, 230);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(292, 100);
            this.groupBox3.Tag = null;
            this.groupBox3.Title = "Latest/Current Instruction";
            this.groupBox3.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(14, 60);
            this.tpsLabel4.Size = new System.Drawing.Size(121, 24);
            this.tpsLabel4.Title = "Workobject:";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(14, 29);
            this.tpsLabel3.Size = new System.Drawing.Size(121, 24);
            this.tpsLabel3.Title = "Target:";
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox4.AutoScroll = false;
            this.groupBox4.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox4.Controls.Add(this.tpsLabel14);
            this.groupBox4.Controls.Add(this.tpsLabel13);
            this.groupBox4.Controls.Add(this.tpsLabel12);
            this.groupBox4.Controls.Add(this.tpsLabel11);
            this.groupBox4.Controls.Add(this.tpsLabel10);
            this.groupBox4.Controls.Add(this.tpsLabel9);
            this.groupBox4.Controls.Add(this.tpsLabel8);
            this.groupBox4.Controls.Add(this.tpsLabel7);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox4.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox4.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox4.Location = new System.Drawing.Point(337, 127);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(275, 203);
            this.groupBox4.Tag = null;
            this.groupBox4.Title = "Progress";
            this.groupBox4.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel14
            // 
            this.tpsLabel14.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel14.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel14.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel14.Location = new System.Drawing.Point(105, 145);
            this.tpsLabel14.Size = new System.Drawing.Size(73, 24);
            this.tpsLabel14.Title = "Step 4";
            // 
            // tpsLabel13
            // 
            this.tpsLabel13.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel13.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel13.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel13.Location = new System.Drawing.Point(105, 103);
            this.tpsLabel13.Size = new System.Drawing.Size(73, 24);
            this.tpsLabel13.Title = "Step 3";
            // 
            // tpsLabel12
            // 
            this.tpsLabel12.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel12.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel12.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel12.Location = new System.Drawing.Point(105, 64);
            this.tpsLabel12.Size = new System.Drawing.Size(73, 24);
            this.tpsLabel12.Title = "Step 2";
            // 
            // tpsLabel11
            // 
            this.tpsLabel11.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel11.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.tpsLabel11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel11.Location = new System.Drawing.Point(105, 22);
            this.tpsLabel11.Size = new System.Drawing.Size(73, 24);
            this.tpsLabel11.Title = "Step 1";
            // 
            // tpsLabel10
            // 
            this.tpsLabel10.BackColor = System.Drawing.Color.BurlyWood;
            this.tpsLabel10.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel10.Location = new System.Drawing.Point(30, 145);
            this.tpsLabel10.Size = new System.Drawing.Size(32, 24);
            this.tpsLabel10.Title = "";
            // 
            // tpsLabel9
            // 
            this.tpsLabel9.BackColor = System.Drawing.Color.LightGray;
            this.tpsLabel9.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel9.Location = new System.Drawing.Point(30, 103);
            this.tpsLabel9.Size = new System.Drawing.Size(32, 24);
            this.tpsLabel9.Title = "";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.BackColor = System.Drawing.Color.Brown;
            this.tpsLabel8.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel8.Location = new System.Drawing.Point(30, 64);
            this.tpsLabel8.Size = new System.Drawing.Size(32, 24);
            this.tpsLabel8.Title = "";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.BackColor = System.Drawing.Color.Tomato;
            this.tpsLabel7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(30, 22);
            this.tpsLabel7.Size = new System.Drawing.Size(32, 24);
            this.tpsLabel7.Title = "";
            // 
            // commandBar1
            // 
            this.commandBar1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.commandBar1.Location = new System.Drawing.Point(0, 347);
            this.commandBar1.MenuItems.Add(this.menuItem1);
            this.commandBar1.Size = new System.Drawing.Size(639, 43);
            // 
            // menuItem1
            // 
            this.menuItem1.Checked = false;
            this.menuItem1.DockToRight = true;
            this.menuItem1.Enabled = true;
            this.menuItem1.Index = 0;
            this.menuItem1.Pressed = false;
            this.menuItem1.Text = "Close";
            this.menuItem1.Toggle = false;
            this.menuItem1.Width = 128;
            this.menuItem1.Click += new System.EventHandler(this.Execution_Close);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(516, 0);
            this.pictureBox1.Size = new System.Drawing.Size(123, 45);
            // 
            // ExecutionStatus
            // 
            this.BackColor = System.Drawing.SystemColors.Window;
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.commandBar1);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox4);
            this.Text = "Execution Status";
            this.Controls.SetChildIndex(this.groupBox4, 0);
            this.Controls.SetChildIndex(this.groupBox3, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.commandBar1, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Execution_Close(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseMe();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Execution_Close", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
